"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { type ReactNode, useEffect, useState } from "react";
import { Bell, CalendarDays, ChartNoAxesCombined, CheckSquare2, CircleHelp, FolderKanban, LayoutDashboard, LogOut, Menu, MoreHorizontal, Search, Settings, UsersRound, X } from "lucide-react";
import { Brand } from "@/components/brand";
import { WorkspaceContentSkeleton } from "@/components/workspace-content-skeleton";
import { initials, cn } from "@/lib/utils";
import { useWorkspace } from "@/components/workspace-provider";

const nav = [
  ["Dashboard", "/dashboard", LayoutDashboard], ["Clients", "/clients", UsersRound], ["Projects", "/projects", FolderKanban], ["Tasks", "/tasks", CheckSquare2], ["Kanban", "/kanban", MoreHorizontal], ["Calendar", "/calendar", CalendarDays], ["Team", "/team", UsersRound], ["Reports", "/reports", ChartNoAxesCombined],
] as const;
const mobile = nav.filter(([label]) => ["Dashboard", "Projects", "Tasks", "Calendar"].includes(label));

export function AppShell({ children }: { children: ReactNode }) {
  const pathname = usePathname();
  const router = useRouter();
  const { data, loading, signOut } = useWorkspace();
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState(false);

  useEffect(() => { if (!loading && !data) router.replace("/login?next=" + encodeURIComponent(pathname)); }, [data, loading, pathname, router]);
  if (!loading && !data) return null;

  const isContentLoading = loading || !data;
  const isActive = (href: string) => pathname === href || (href !== "/dashboard" && pathname.startsWith(href));
  const sideContent = <><div className="mb-8 flex items-center justify-between px-1"><Brand/><button onClick={() => setOpen(false)} className="lg:hidden"><X size={19}/></button></div><nav className="space-y-1" aria-label="Application navigation">{nav.map(([label, href, Icon]) => <Link key={href} onClick={() => setOpen(false)} href={href} className={cn("focus-ring flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition", isActive(href) ? "bg-[#EEF2EA] text-[#294737]" : "text-[#697068] hover:bg-[#F7F8F5] hover:text-[#172033]")}><Icon size={17}/>{label}</Link>)}</nav><div className="mt-auto border-t border-[#E3E5DF] pt-4"><Link href="/settings" className={cn("focus-ring flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium", isActive("/settings") ? "bg-[#EEF2EA] text-[#294737]" : "text-[#697068] hover:bg-[#F7F8F5]")}><Settings size={17}/>Settings</Link><Link href="/help" className="focus-ring flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-[#697068] hover:bg-[#F7F8F5]"><CircleHelp size={17}/>Help center</Link><button onClick={async () => { await signOut(); router.push("/"); }} className="focus-ring flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium text-[#697068] hover:bg-red-50 hover:text-[#C95454]"><LogOut size={17}/>Sign out</button></div></>;

  return <div className="min-h-screen bg-[#F7F8F5]"><aside className="fixed inset-y-0 left-0 z-40 hidden w-[244px] flex-col border-r border-[#E3E5DF] bg-white p-5 lg:flex">{sideContent}</aside>{open && <><button aria-label="Close menu" onClick={() => setOpen(false)} className="fixed inset-0 z-40 bg-[#172033]/30 lg:hidden"/><aside className="fixed inset-y-0 left-0 z-50 flex w-[282px] flex-col bg-white p-5 shadow-panel lg:hidden">{sideContent}</aside></>}<main className="pb-20 lg:ml-[244px] lg:pb-0"><header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-[#E3E5DF] bg-white/90 px-4 backdrop-blur lg:px-8"><button onClick={() => setOpen(true)} className="focus-ring rounded-md p-2 lg:hidden" aria-label="Open navigation"><Menu size={21}/></button><button disabled={isContentLoading} onClick={() => setSearch(true)} className="focus-ring hidden w-[340px] items-center gap-2 rounded-lg border border-[#E3E5DF] bg-[#FAF9F6] px-3 py-2 text-left text-xs text-[#98a2b3] disabled:cursor-wait disabled:opacity-70 md:flex"><Search size={15}/>Search anything… <kbd className="ml-auto rounded border border-[#E3E5DF] bg-white px-1.5 py-0.5 text-[10px]">⌘ K</kbd></button><div className="flex items-center gap-2 sm:gap-4">{!isContentLoading && data ? <span className="hidden rounded-full bg-[#EEF2EA] px-2.5 py-1 text-[11px] font-semibold text-[#355C45] sm:inline">{data.workspace.is_demo ? "Demo workspace" : data.workspace.name}</span> : <span aria-label="Loading workspace" className="hidden h-7 w-28 animate-pulse rounded-full bg-[#EEF2EA] sm:inline"/>}<button className="focus-ring relative rounded-lg p-2 text-[#697068] hover:bg-[#F7F8F5]" aria-label="Notifications"><Bell size={18}/><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-[#3F7A53]"/></button>{!isContentLoading && data ? <Link href="/settings" className="focus-ring grid size-9 place-items-center rounded-full bg-[#355C45] text-xs font-bold text-white">{initials(data.profile.full_name)}</Link> : <span aria-label="Loading profile" className="size-9 animate-pulse rounded-full bg-[#DDE5D8]"/>}</div></header><div className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">{isContentLoading ? <WorkspaceContentSkeleton/> : children}</div></main><nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-5 border-t border-[#E3E5DF] bg-white px-1 py-1.5 lg:hidden">{mobile.map(([label, href, Icon]) => <Link href={href} key={href} className={cn("focus-ring grid place-items-center gap-1 rounded-lg py-1 text-[10px] font-medium", isActive(href) ? "text-[#355C45]" : "text-[#7c8595]")}><Icon size={17}/>{label}</Link>)}<button onClick={() => setOpen(true)} className="focus-ring grid place-items-center gap-1 rounded-lg py-1 text-[10px] font-medium text-[#7c8595]"><MoreHorizontal size={17}/>More</button></nav>{search && <SearchDialog close={() => setSearch(false)}/>}</div>;
}

function SearchDialog({ close }: { close: () => void }) { const { data } = useWorkspace(); const [term, setTerm] = useState(""); const q = term.toLowerCase(); const results = data ? [...data.clients.map((item) => ({ type: "Client", id: item.id, name: item.name, href: `/clients/${item.id}` })), ...data.projects.map((item) => ({ type: "Project", id: item.id, name: item.name, href: `/projects/${item.id}` })), ...data.tasks.map((item) => ({ type: "Task", id: item.id, name: item.title, href: "/tasks" }))].filter((item) => item.name.toLowerCase().includes(q)).slice(0, 7) : []; return <div className="fixed inset-0 z-[70] grid place-items-start bg-[#172033]/35 px-4 pt-[14vh]" role="dialog" aria-modal="true"><button className="absolute inset-0" onClick={close} aria-label="Close search"/><div className="relative w-full max-w-xl overflow-hidden rounded-2xl border border-[#E3E5DF] bg-white shadow-panel"><div className="flex items-center gap-3 border-b border-[#E3E5DF] px-4"><Search size={18} className="text-[#697068]"/><input autoFocus value={term} onChange={(e) => setTerm(e.target.value)} placeholder="Search clients, projects, and tasks…" className="h-14 w-full border-0 bg-transparent text-sm outline-none"/><button onClick={close} className="rounded border px-1.5 text-xs text-[#697068]">ESC</button></div><div className="max-h-80 overflow-y-auto p-2">{results.length ? results.map((result) => <Link onClick={close} key={`${result.type}-${result.id}`} href={result.href} className="flex items-center justify-between rounded-lg px-3 py-3 hover:bg-[#F7F8F5]"><span className="text-sm font-medium">{result.name}</span><span className="text-xs text-[#697068]">{result.type}</span></Link>) : <p className="px-3 py-8 text-center text-sm text-[#697068]">{term ? "No matching work found." : "Start typing to search your workspace."}</p>}</div></div></div>; }
