"use client";

import { type ReactNode } from "react";
import { Search, X } from "lucide-react";
import { cn, initials } from "@/lib/utils";

export function Button({ children, className, variant = "primary", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "quiet" | "danger" }) { const styles = { primary: "bg-[#355C45] text-white hover:bg-[#294737] shadow-sm", secondary: "border border-[#E3E5DF] bg-white text-[#172033] hover:bg-[#F7F8F5]", quiet: "text-[#697068] hover:bg-[#F7F8F5]", danger: "bg-[#C95454] text-white hover:bg-[#af4040]" }; return <button {...props} className={cn("focus-ring inline-flex items-center justify-center gap-2 rounded-lg px-3.5 py-2.5 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50", styles[variant], className)}>{children}</button>; }
export function PageHeading({ eyebrow, title, copy, action }: { eyebrow?: string; title: string; copy?: string; action?: ReactNode }) { return <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow && <p className="mb-1 text-xs font-bold uppercase tracking-[.14em] text-[#355C45]">{eyebrow}</p>}<h1 className="text-2xl font-bold tracking-[-.045em] text-[#172033] sm:text-[28px]">{title}</h1>{copy && <p className="mt-1.5 max-w-2xl text-sm leading-6 text-[#697068]">{copy}</p>}</div>{action && <div className="shrink-0">{action}</div>}</div>; }
export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: "violet" | "green" | "amber" | "red" | "neutral" }) { const tones = { violet: "bg-[#EEF2EA] text-[#355C45]", green: "bg-[#eaf4ec] text-[#3F7A53]", amber: "bg-[#fff4e5] text-[#b76c16]", red: "bg-[#fbecec] text-[#C95454]", neutral: "bg-[#f1f3ef] text-[#697068]" }; return <span className={cn("inline-flex whitespace-nowrap rounded-md px-2 py-1 text-[11px] font-semibold", tones[tone])}>{children}</span>; }
export function Avatar({ name, className }: { name: string; className?: string }) { return <span className={cn("grid size-8 shrink-0 place-items-center rounded-full bg-[#EEF2EA] text-[10px] font-bold text-[#355C45]", className)}>{initials(name)}</span>; }
export function Progress({ value, className }: { value: number; className?: string }) { return <div className={cn("h-2 overflow-hidden rounded-full bg-[#EEF2EA]", className)}><div className="h-full rounded-full bg-[#355C45]" style={{ width: `${Math.min(100, Math.max(0, value))}%` }}/></div>; }
export function SearchInput({ value, onChange, placeholder = "Search…", className }: { value: string; onChange: (value: string) => void; placeholder?: string; className?: string }) { return <label className={cn("flex h-10 items-center gap-2 rounded-lg border border-[#E3E5DF] bg-white px-3 text-[#98a2b3]", className)}><Search size={15}/><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent text-sm text-[#172033] outline-none placeholder:text-[#98a2b3]"/></label>; }
export function EmptyState({ icon, title, copy, action }: { icon: ReactNode; title: string; copy: string; action?: ReactNode }) { return <div className="grid min-h-64 place-items-center rounded-xl border border-dashed border-[#d7dbe4] bg-white p-8 text-center"><div><div className="mx-auto mb-3 grid size-11 place-items-center rounded-xl bg-[#EEF2EA] text-[#355C45]">{icon}</div><h3 className="font-semibold">{title}</h3><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-[#697068]">{copy}</p>{action && <div className="mt-4">{action}</div>}</div></div>; }
export function Modal({ title, children, close, footer, wide = false }: { title: string; children: ReactNode; close: () => void; footer?: ReactNode; wide?: boolean }) { return <div className="fixed inset-0 z-[80] grid place-items-center bg-[#172033]/35 p-4" role="dialog" aria-modal="true" aria-label={title}><button onClick={close} aria-label="Close dialog" className="absolute inset-0"/><div className={cn("relative max-h-[90vh] w-full overflow-y-auto rounded-2xl border border-[#E3E5DF] bg-white shadow-panel", wide ? "max-w-2xl" : "max-w-lg")}><div className="flex items-center justify-between border-b border-[#E3E5DF] px-5 py-4"><h2 className="text-base font-bold">{title}</h2><button onClick={close} className="focus-ring rounded-lg p-1.5 text-[#697068] hover:bg-[#F7F8F5]"><X size={18}/></button></div><div className="p-5">{children}</div>{footer && <div className="flex justify-end gap-2 border-t border-[#E3E5DF] bg-[#FAF9F6] px-5 py-4">{footer}</div>}</div></div>; }
export function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="block text-sm font-medium text-[#344054]"><span className="mb-1.5 block">{label}</span>{children}{error && <span className="mt-1 block text-xs text-red-600">{error}</span>}</label>; }
export const inputClass = "focus-ring h-10 w-full rounded-lg border border-[#E3E5DF] bg-white px-3 text-sm text-[#172033] outline-none placeholder:text-[#98a2b3]";
